include $(GOROOT)/src/Make.$(GOARCH)

TARG=gospec
GOFILES=\
	context.go\
	error.go\
	funcname.go\
	location.go\
	main.go\
	matchers.go\
	printer.go\
	print_format.go\
	results.go\
	runner.go\
	specification.go\

include $(GOROOT)/src/Make.pkg

